name: op-community-hub-scraper

on:
  schedule:
    - cron: "0 4 * * *" # at 4:00 UTC
  workflow_dispatch: # also manually

jobs:
  scrap:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Run script
        run: bash ./run.sh

      - name: Create ZIP with .md
        run: |
          zip -r kb.zip output/

      - name: Generate last update timestamp
        run: |
          echo "{\"last_update\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > output/last-update.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: daily
          name: Knowledge Base Daily Auto Release
          files: |
            kb.zip
            output/last-update.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
